---
name: 3. Teamarbeit
description: Themen rund um die Teamarbeit
title: "[Teamarbeit]: "
labels: ["Teamarbeit"]
body:
  - type: markdown
    attributes:
      value: |
        **Themenbezogene Aufgaben f체r Teamarbeit**
  - type: checkboxes
    id: teamarbeit-themen
    attributes:
      label: W채hle die relevanten Themen
      options:
        - label: Phasen der Teamentwicklung (Forming, Storming, Norming, Performing, Adjourning)
        - label: Reflexion, Feedback-Kultur, Lessons Learned
        - label: Win-Win-Strategie, Harvard-Konzept
        - label: Kommunikationsmodelle (4-Ohren-Modell, Sender-Empf채nger)
        - label: Diversity, Interkulturalit채t
  - type: markdown
    id: Referenz
    attributes:
      value: "Quellenangabe: Kommunikation mit ChatGTP, Model o3-mini"
