name: "Trainingsbeitrag"
title: "[??:??] [Themenbereich] [Titel]"
description: "Ein einfaches Issue-Template für die Erstellung eines Trainingsbeitrags der AP 1"
labels: ["documentation", "Trainingsbeitrag", "Abschlussprüfung 1"]
assignees: []

body:
  - type: dropdown
    id: themenbereich
    attributes:
      label: "Wählen des Themenbereich für den Trainingsbeitrag"
      description: "Auswahl eines Themenbereichs für den Trainingsbeitrag."
      options:
        - "01-01 Merkmale und Methoden des Projektmanagements kennen, beurteilen, anwenden können"
        - "01-02 Machbarkeit und Wirtschaftlichkeit von Projekten beurteilen können"
        - "01-03 Arbeitsaufgaben im Rahmen von Geschäfts- und Leistungsprozessen planen, vorbereiten und durchführen"
        - "01-04 Phasen der Teambildung"
        - "02-01 Marktsituationen bewerten"
        - "02-02 Zielgruppengerechte Bedarfsanalyse"
        - "02-03 Zielgerichtete Methoden zur Kundenberatung"
        - "02-04 Informationen aufbereiten und präsentieren"
        - "02-05 Marketingaktivitäten unterstützen"
        - "03-01 Marktgängige IT-Systeme kennen"
        - "03-02 Typische IT-Systeme und deren Einsatzbereiche"
        - "03-03 Leistungsfähigkeit und Energieeffizienz"
        - "03-04 Wirtschaftlichkeit von IT-Systemen"
        - "04-01 IT-Systeme konzeptionieren"
        - "04-02 Bedarfsgerechte Hardware Auswahl"
        - "04-03 Bedarfsgerechte Software Auswahl"
        - "04-04 Urheberrechtsgesetz und Lizenzmodelle"
        - "04-05 Installations- und Konfigurationsaktivitäten"
        - "04-06 Programmiersprachen"
        - "04-07 Programmierwerkzeuge"
        - "04-08 Grundlagen von relationalen Datenbanken"
        - "05-01 QM-Grundverständnis"
        - "05-02 Maßnahmen des Qualitätsmanagements"
        - "06-01 IT-Sicherheit und Datenschutz"
        - "06-02 Schutzbedarfsanalyse durchführen"
        - "06-03 Sicherheitskonzept modellieren"
        - "06-04 Sicherheitskonzept umsetzen"
        - "07-01 Vertragsarten und Vertragsstörungen"
        - "07-02 Zielsetzungen des Unternehmens"
        - "07-03 Leistungserbringung Varianten"
        - "07-04 Abstimmung der Leistungserbringung"
        - "07-05 Veränderungsprozesse begleiten"
        - "07-06 Leistungsübergabe und Einweisung"
        - "07-07 Leistungserbringung bewerten"
  - type: textarea
    id: beitrag
    attributes:
      label: "Trainingsbeitrag"
      description: "Bitte den Trainingsbeitrag im Markdown-Format eintragen."
      placeholder: "# [Subthema]\n\n## Inhalt\n\n"
  - type: textarea
    id: subthema
    attributes:
      label: "Aufgaben"
      description: "Bitte die Issues der Aufgaben als Checkliste eintragen."
      placeholder: "- [ ] Aufgabe 1\n- [ ] Aufgabe 2\n- [ ] Aufgabe 3\n"
  - type: checkboxes
    id: sub-issues
    attributes:
      label: Sub-Issues
      description: Verknüpfte Issues
      options:
        - label: "Aufgabe 1"
        - label: "Aufgabe 2"
        - label: "Aufgabe 3"

      