---
name: 6. Kundenberatung und Pr채sentieren
description: Themen rund um Kundenberatung und Pr채sentationen
title: "[Kundenberatung]: "
labels: ["Kundenberatung"]
body:
  - type: checkboxes
    id: kundenberatung-themen
    attributes:
      label: W채hle die relevanten Themen
      options:
        - label: Pr채sentationstechniken
        - label: Zielgruppengerechte Kommunikation
        - label: Nutzung von Fachquellen in Deutsch und Englisch
  - type: markdown
    id: Referenz
    attributes:
      value: "Quellenangabe: Kommunikation mit ChatGTP, Model o3-mini"
